<a href="https://colab.research.google.com/github/gnani321/basic-ds-/blob/main/chisquare.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = pd.DataFrame({"satisification": ["very satisified","satisfied","neutral","unsatisified","very unsatisified","Total"],
                    "Smart Thermostat":[50,80,60,30,20,240],
                     "Smart Light":[70,100,90,50,50,360],
                     "Total":[120,180,150,80,70,600]})

In [ ]:
data

satisification  Smart Thermostat  Smart Light  Total
0    very satisified                50           70    120
1          satisfied                80          100    180
2            neutral                60           90    150
3       unsatisified                30           50     80
4  very unsatisified                20           50     70
5              Total               240          360    600

# STATE THE HYPOTHESES

NULL HYPOTHESES(Ho) :There is no significant association between the type of device and customer



ALTERNATIVE HYPOTHESIS(H1):There is  significant association between the type of device and customer


In [ ]:
# given from the data
observed=data[["Smart Thermostat", "Smart Light"]].iloc[:-1].to_numpy()
observed

array([[ 50,  70],
       [ 80, 100],
       [ 60,  90],
       [ 30,  50],
       [ 20,  50]])

In [ ]:
#sum of each rows
row_sum=np.sum(observed,axis=1)
row_sum


array([120, 180, 150,  80,  70])

In [ ]:
# sum of each  columns
column_sum=np.sum(observed,axis=0)
column_sum

array([240, 360])

In [ ]:
# grand total of all entries
grand_total=np.sum(observed)
grand_total

600

In [ ]:
#calculate the expected frequency
expected=np.outer(row_sum,column_sum)/grand_total
expected

array([[ 48.,  72.],
       [ 72., 108.],
       [ 60.,  90.],
       [ 32.,  48.],
       [ 28.,  42.]])

In [ ]:
# calculate the Chi-squre statstic
chi_square_statstic=np.sum((observed-expected)**2/expected)
chi_square_statstic

5.638227513227513

In [ ]:
# degress of freedom
df=(observed.shape[0]-1)*(observed.shape[1]-1)
df

4

In [ ]:
#alpha value
alpha=0.05

In [ ]:
# calculate the critical value from chisqaure distribution
from scipy.stats import chi2
from scipy.stats import stats
critical_value=chi2.ppf(1-alpha,df)
critical_value

9.487729036781154

In [ ]:
 # compare the chi-square statistic with the critical value to make a decision
if chi_square_statstic>critical_value:
    print("Reject the null hypothesis.There is significant association between the type of device and customer")
else:
    print("Fail to reject the null hypothesis.There is no significant association between the type of device and customer")

Fail to reject the null hypothesis.There is no significant association between the type of device and customer


1.Null Hypothesis (H₀): There is no significant association between the type of device and customer satisfaction.

2.Alternative Hypothesis (H₁): There is a significant association between the type of device and customer satisfaction.

3.Based on the Chi-Square statistic and critical value comparison, the null hypothesis is not rejected in this case.